"""Initial schema

Revision ID: 9e32029f9fff
Revises: 
Create Date: 2026-03-25 17:22:05.057864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e32029f9fff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number_masked', sa.String(), nullable=False),
    sa.Column('ifsc_code_optional', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('counterparties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('relationship_tier', sa.String(), nullable=True),
    sa.Column('relationship_notes', sa.String(), nullable=True),
    sa.Column('relationship_score_numeric', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparties_user_id'), 'counterparties', ['user_id'], unique=False)
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type_a', sa.String(), nullable=False),
    sa.Column('source_id_a', sa.UUID(), nullable=False),
    sa.Column('source_type_b', sa.String(), nullable=False),
    sa.Column('source_id_b', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.Column('signals_used_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_matches_user_id'), 'reconciliation_matches', ['user_id'], unique=False)
    op.create_table('scenario_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('assumptions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_snapshots_user_id'), 'scenario_snapshots', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id_nullable', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename_uuid', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('upload_source', sa.String(), nullable=True),
    sa.Column('upload_status', sa.String(), nullable=True),
    sa.Column('ocr_status', sa.String(), nullable=True),
    sa.Column('extracted_payload_json', sa.JSON(), nullable=True),
    sa.Column('error_message_nullable', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id_nullable'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_bank_account_id_nullable'), 'documents', ['bank_account_id_nullable'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value_date_nullable', sa.Date(), nullable=True),
    sa.Column('description_raw', sa.String(), nullable=False),
    sa.Column('description_normalized', sa.String(), nullable=True),
    sa.Column('debit_amount_nullable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credit_amount_nullable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('balance_after_nullable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reference_number_nullable', sa.String(), nullable=True),
    sa.Column('parsed_ok_boolean', sa.Boolean(), nullable=True),
    sa.Column('parse_error_message_nullable', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_source_document_id'), 'bank_transactions', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_user_id'), 'bank_transactions', ['user_id'], unique=False)
    op.create_table('financial_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id_nullable', sa.UUID(), nullable=True),
    sa.Column('counterparty_id_nullable', sa.UUID(), nullable=True),
    sa.Column('source_document_id_nullable', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('value_date_nullable', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('raw_metadata_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score_numeric', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id_nullable'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id_nullable'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['source_document_id_nullable'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_events_bank_account_id_nullable'), 'financial_events', ['bank_account_id_nullable'], unique=False)
    op.create_index(op.f('ix_financial_events_counterparty_id_nullable'), 'financial_events', ['counterparty_id_nullable'], unique=False)
    op.create_index(op.f('ix_financial_events_event_date'), 'financial_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_financial_events_event_type'), 'financial_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_financial_events_source_document_id_nullable'), 'financial_events', ['source_document_id_nullable'], unique=False)
    op.create_index(op.f('ix_financial_events_status'), 'financial_events', ['status'], unique=False)
    op.create_index(op.f('ix_financial_events_user_id'), 'financial_events', ['user_id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id_nullable', sa.UUID(), nullable=True),
    sa.Column('source_document_id_nullable', sa.UUID(), nullable=True),
    sa.Column('linked_bank_transaction_id_nullable', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('flexibility_score', sa.Float(), nullable=True),
    sa.Column('daily_penalty_rate_nullable', sa.Float(), nullable=True),
    sa.Column('penalty_profile_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id_nullable'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['linked_bank_transaction_id_nullable'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['source_document_id_nullable'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_counterparty_id_nullable'), 'obligations', ['counterparty_id_nullable'], unique=False)
    op.create_index(op.f('ix_obligations_due_date'), 'obligations', ['due_date'], unique=False)
    op.create_index(op.f('ix_obligations_linked_bank_transaction_id_nullable'), 'obligations', ['linked_bank_transaction_id_nullable'], unique=False)
    op.create_index(op.f('ix_obligations_source_document_id_nullable'), 'obligations', ['source_document_id_nullable'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_index(op.f('ix_obligations_user_id'), 'obligations', ['user_id'], unique=False)
    op.create_table('receivables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id_nullable', sa.UUID(), nullable=True),
    sa.Column('source_document_id_nullable', sa.UUID(), nullable=True),
    sa.Column('linked_bank_transaction_id_nullable', sa.UUID(), nullable=True),
    sa.Column('invoice_number_nullable', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('expected_arrival_date_nullable', sa.Date(), nullable=True),
    sa.Column('confidence_band', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_lag_stats_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id_nullable'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['linked_bank_transaction_id_nullable'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['source_document_id_nullable'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivables_counterparty_id_nullable'), 'receivables', ['counterparty_id_nullable'], unique=False)
    op.create_index(op.f('ix_receivables_due_date'), 'receivables', ['due_date'], unique=False)
    op.create_index(op.f('ix_receivables_linked_bank_transaction_id_nullable'), 'receivables', ['linked_bank_transaction_id_nullable'], unique=False)
    op.create_index(op.f('ix_receivables_source_document_id_nullable'), 'receivables', ['source_document_id_nullable'], unique=False)
    op.create_index(op.f('ix_receivables_status'), 'receivables', ['status'], unique=False)
    op.create_index(op.f('ix_receivables_user_id'), 'receivables', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivables_user_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_status'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_source_document_id_nullable'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_linked_bank_transaction_id_nullable'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_due_date'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_counterparty_id_nullable'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_obligations_user_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_source_document_id_nullable'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_linked_bank_transaction_id_nullable'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_due_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_counterparty_id_nullable'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_financial_events_user_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_status'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_source_document_id_nullable'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_event_type'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_event_date'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_counterparty_id_nullable'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_bank_account_id_nullable'), table_name='financial_events')
    op.drop_table('financial_events')
    op.drop_index(op.f('ix_bank_transactions_user_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_source_document_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_bank_account_id_nullable'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_scenario_snapshots_user_id'), table_name='scenario_snapshots')
    op.drop_table('scenario_snapshots')
    op.drop_index(op.f('ix_reconciliation_matches_user_id'), table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_index(op.f('ix_counterparties_user_id'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
