// @ML-PROMPT:
// Read CLAUDE.md. Build a cash flow anomaly detection module for CaliComp.
// Goal: detect when a transaction or obligation is statistically unusual compared to historical patterns.
// Implementation in backend/app/ml/anomaly_detector.py:
// 1. For each transaction category: compute rolling 3-month mean and std of transaction amounts.
// 2. Flag any new transaction where |amount - mean| > 2 * std as anomalous.
// 3. Use Isolation Forest (sklearn.ensemble.IsolationForest) on the full transaction feature vector.
// 4. Anomalies surfaced as HIGH priority insight: "Unusual ₹[amount] for [vendor] — [X]% above typical invoice."
// 5. Expose as: GET /api/v1/ml/anomalies
// Retrain weekly. Store model at backend/models/anomaly_model.pkl

import React, { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { clsx } from 'clsx';
import { Sparkles, RefreshCw, ChevronRight, Loader, Info, ChevronDown, ChevronUp } from 'lucide-react';
import { ProGate } from '../components/ui/ProGate';
import { Button, Badge } from '../components/ui/Common';
import { generateInsights } from '../services/aiInsights';
import type { AIInsight } from '../types';

const PRIORITY_COLOR: Record<AIInsight['priority'], 'danger' | 'warning' | 'success'> = {
  HIGH:   'danger',
  MEDIUM: 'warning',
  LOW:    'success',
};

const CATEGORY_LABEL: Record<AIInsight['category'], string> = {
  DEFERRAL:   'Deferral Opportunity',
  COLLECTION: 'Collection Action',
  COMPLIANCE: 'Compliance Risk',
  CASHFLOW:   'Cash Flow',
};

const CATEGORY_COLOR: Record<AIInsight['category'], string> = {
  DEFERRAL:   'text-blue-400',
  COLLECTION: 'text-purple-400',
  COMPLIANCE: 'text-red-400',
  CASHFLOW:   'text-green-400',
};

export default function AIInsights() {
  const navigate = useNavigate();
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading]   = useState(true);
  const [lastRefresh, setLastRefresh] = useState<Date | null>(null);
  const [disclaimerOpen, setDisclaimerOpen] = useState(false);

  const load = useCallback(() => {
    setLoading(true);
    generateInsights().then((data) => {
      setInsights(data);
      setLoading(false);
      setLastRefresh(new Date());
    });
  }, []);

  useEffect(() => { load(); }, [load]);

  return (
    <div className="space-y-8 max-w-3xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-black text-white tracking-tight">AI Insights</h2>
          <p className="text-sm text-gray-500 font-medium mt-1 uppercase tracking-widest">
            GPT-4o financial recommendations
            {lastRefresh && ` · Last updated ${lastRefresh.toLocaleTimeString()}`}
          </p>
        </div>
        <Button
          variant="outline"
          className="flex items-center gap-2"
          onClick={load}
          disabled={loading}
        >
          <RefreshCw className={clsx('w-4 h-4', loading && 'animate-spin')} />
          Refresh Insights
        </Button>
      </div>

      {/* Collapsible AI disclaimer */}
      <div className="bg-[#111827] border border-gray-800 rounded-xl overflow-hidden">
        <button
          onClick={() => setDisclaimerOpen(v => !v)}
          className="w-full flex items-center gap-2 px-4 py-3 hover:bg-gray-800/30 transition-colors text-left"
        >
          <Info className="w-3.5 h-3.5 text-blue-400 shrink-0" />
          <span className="text-xs font-bold text-gray-400 flex-1">ⓘ About AI-generated insights</span>
          {disclaimerOpen
            ? <ChevronUp   className="w-3.5 h-3.5 text-gray-600" />
            : <ChevronDown className="w-3.5 h-3.5 text-gray-600" />}
        </button>
        {disclaimerOpen && (
          <div className="px-4 pb-4 border-t border-gray-800/60">
            <p className="text-xs text-gray-400 leading-relaxed pt-3">
              These insights are generated by an AI model (GPT-4o) based on your financial data. They are
              mathematical observations, not financial advice. AI models can make errors. Always verify
              insights against your actual records and consult a financial advisor before acting on any
              recommendation.
            </p>
          </div>
        )}
      </div>

      {/* ProGate wraps full content */}
      <ProGate featureName="AI Insights" fullPage>
        {loading ? (
          <div className="flex flex-col items-center gap-4 py-20">
            <Loader className="w-10 h-10 text-blue-400 animate-spin" />
            <p className="text-sm font-bold text-gray-300">Analysing your financial data…</p>
            <p className="text-xs text-gray-500">This usually takes 1–2 seconds</p>
          </div>
        ) : (
          <div className="space-y-5">
            {insights.map((ins, idx) => (
              <div
                key={ins.id}
                className="bg-[#111827] border border-gray-800 rounded-2xl p-6 space-y-4"
              >
                {/* Top row */}
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="w-8 h-8 rounded-xl bg-blue-900/20 border border-blue-900/30 flex items-center justify-center shrink-0">
                      <Sparkles className={clsx('w-4 h-4', CATEGORY_COLOR[ins.category])} />
                    </div>
                    <div className="min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-[9px] font-black text-gray-600 uppercase tracking-widest">#{idx + 1}</span>
                        <span className="text-[10px] font-bold text-gray-500">{CATEGORY_LABEL[ins.category]}</span>
                      </div>
                      <p className="text-sm font-black text-white mt-0.5">{ins.title}</p>
                    </div>
                  </div>
                  <Badge variant={PRIORITY_COLOR[ins.priority]}>{ins.priority}</Badge>
                </div>

                {/* Body */}
                <p className="text-xs text-gray-400 leading-relaxed pl-11">{ins.body}</p>

                {/* Footer */}
                <div className="flex items-center justify-between pl-11">
                  <div className="flex items-center gap-2">
                    <span className="text-[10px] text-gray-600 font-bold uppercase tracking-widest">Impact</span>
                    <span className="text-sm font-black text-green-400">{ins.impact}</span>
                  </div>
                  <button
                    onClick={() => navigate(ins.actionRoute)}
                    className="flex items-center gap-1 text-xs font-bold text-blue-400 hover:text-blue-300 transition-colors px-3 py-1.5 rounded-lg hover:bg-blue-900/20"
                  >
                    {ins.actionLabel} <ChevronRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))}

            <p className="text-[10px] text-gray-600 text-center pt-2">
              Insights generated by GPT-4o · Financial calculations use deterministic logic, not AI
            </p>
          </div>
        )}
      </ProGate>
    </div>
  );
}
